### ISSUE TITLE
nbm file cant' exist anymore on www.nitcorn.ch

### ISSUE THREAD

**Issue by LegolasTheElf** [mvetsch/VirusTotalOnlineChecker#1]
unfortunately, the provided link to www.nitcorn.ch to download org-sleuthkit-autopsy-modules-virustotalonlinecheck.nbm doesn't work anymore (404)
are there around another way to retrieve an NBM file ? or the zip file for python plugin installation?

Thanks a lot

**Comment by mvetsch** [comment]
Sorry about that. The release is now available on Github on the releases tab of the project. Github seems to be more reliable.
