### ISSUE TITLE
How to install 

### ISSUE THREAD

**Issue by devzeroo** [mvetsch/VirusTotalOnlineChecker#3]
Any tips on how to install this ingest module ?

**Comment by doomguy** [comment]
Have a look here: https://sleuthkit.org/autopsy/docs/user-docs/3.1/module_install_page.html
I suppose you need to use the nbm file from [releases](https://github.com/mvetsch/VirusTotalOnlineChecker/releases).

**Comment by mvetsch** [comment]
Thanks @doomguy
