### ISSUE TITLE
VirusTotal now allows academic licenses which allow much higher rates

### ISSUE THREAD

**Issue by MrHobbits** [mvetsch/VirusTotalOnlineChecker#4]
Currently,
It looks like the module is hard coded to use only 4 requests per minute. VirusTotal now allows people to request academic licenses which allow them to request 1000 per minute, up to 20,000 per day, and 600,000 per month.

We need a way to let the program know our license isn't stuck at 4 requests per minute. Maybe in the ingest module area where we put the key?

**Comment by mvetsch** [comment]
Sweet. I don't actively maintain this module, but I am happy to merge a pull request for academic licenses support.

**Comment by MrHobbits** [comment]
Thank you. I'll see if I can get it to compile/build and make an nbm to test. One issue I'm running into is when I try to build your code (without modification) it results in a few errors that I'm not savvy enough to fumble through. 

Are you able to build using the latest NetBeans and maybe re-upload that? (Not modifying any source or anything new, just rebuilding with the latest NetBeans build as a lot has changed in 5-6 years and I don't think the code here works in the newest versions.
